outdir : /home/liteul/memoir_code/GRIDS/LSST_bu26_5/23/minus0
interpolation-type : tensorflow 
em-model : Bu2026_MLP
em-transient-class : fiesta_kn
label : minus0_23
prior-file :  /home/liteul/memoir_code/GRIDS/prior/bu26.prior
nlive : 512
sampler : pymultinest
light-curve-data : /home/liteul/memoir_code/GRIDS/LSST_bu26_5/23/data23.dat
trigger-time : 61721.0942446875
bestfit : True
filters : ['ps1::y', 'ps1::i', 'ps1::z']
local-only : False
plot : True
xlim : [-2, 12]
ylim : [24, 16]
