outdir : /home/liteul/memoir_code/GRIDS/LSST_bu26_5/10/minus0
interpolation-type : tensorflow 
em-model : Bu2026_MLP
em-transient-class : fiesta_kn
label : minus0_10
prior-file :  /home/liteul/memoir_code/GRIDS/prior/bu26.prior
nlive : 512
sampler : pymultinest
light-curve-data : /home/liteul/memoir_code/GRIDS/LSST_bu26_5/10/data10.dat
trigger-time : 63195.17057362269
bestfit : True
filters : ['ps1::z', 'ps1::i']
local-only : False
plot : True
xlim : [-2, 12]
ylim : [24, 16]
