[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kn_to_gw_search"
version = "0.1.2"
description = "An addon package for PyCBC and NMMA/FIESTA, includes a PyCBC coherent search pipeline generator targeted at BNS and a KN synthetic lightcurve generator based on NMMA."
dependencies = [
    "numpy",
    "pandas",
    "h5py",
    "pyyaml",
    "astropy",
    "matplotlib",
    "gwpy",
    "gwosc",
    "pycbc",
    "scipy",
]

[project.scripts]
# GW search commands
gw-setup-pipeline = "gw_search.setup_pipeline:main"
gw-search-prep = "gw_search.GWsearch_prep:main"
gw-search-post = "gw_search.GWsearch_post:main"
# KN side commands
kn-make-grid = "KN_side.make_grid:main"
kn-ts-loop = "KN_side.ts_infer:main"