outdir : /home/stu_jamsin/memoir_grid/ka17_copy/0/minus4
interpolation-type : tensorflow
em-model : Ka2017
em-transient-class : svd
svd-path : /home/stu_jamsin/jamsin/NMMA/svdmodels 
label : minus4_0
prior-file :  /home/stu_jamsin/memoir_grid/prior/ka17.prior
nlive : 512
sampler : pymultinest
light-curve-data : /home/stu_jamsin/memoir_grid/ka17_copy/0/data_minus4.dat
trigger-time : 58863.3
bestfit : True
filters : ['ps1::g', 'ps1::r', 'ps1::i', 'ps1::z', 'ps1::y']
local-only : False
plot : True
xlim : [-2, 12]
ylim : [24, 16]
