outdir : /home/liteul/memoir_code/GRIDS/LSST_bu26_5/8/minus0
interpolation-type : tensorflow 
em-model : Bu2026_MLP
em-transient-class : fiesta_kn
label : minus0_8
prior-file :  /home/liteul/memoir_code/GRIDS/prior/bu26.prior
nlive : 512
sampler : pymultinest
light-curve-data : /home/liteul/memoir_code/GRIDS/LSST_bu26_5/8/data8.dat
trigger-time : 62680.96966458333
bestfit : True
filters : ['ps1::r', 'ps1::i', 'ps1::z', 'sdssu']
local-only : False
plot : True
xlim : [-2, 12]
ylim : [24, 16]
