outdir : /home/liteul/memoir_code/GRIDS/LSST_bu26_5/7/minus0
interpolation-type : tensorflow 
em-model : Bu2026_MLP
em-transient-class : fiesta_kn
label : minus0_7
prior-file :  /home/liteul/memoir_code/GRIDS/prior/bu26.prior
nlive : 512
sampler : pymultinest
light-curve-data : /home/liteul/memoir_code/GRIDS/LSST_bu26_5/7/data7.dat
trigger-time : 63107.97324331018
bestfit : True
filters : ['ps1::i', 'ps1::z', 'ps1::y']
local-only : False
plot : True
xlim : [-2, 12]
ylim : [24, 16]
